#!/usr/bin/env node
/**
 * compile-content.mjs — validate + emit authored JSON content.
 *
 * Reads config/raw/runes/*.json, validates each against a Zod
 * schema, expands procedural `templatePoints` shapes (the circle
 * marker for the shield rune), and emits a typed TS module at
 * config/compiled/content.ts.
 *
 * Runs as predev / prebuild / pretypecheck / pretest:{node,dom,browser}
 * so authored edits are live without a manual build.
 */

import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..");
const rawRoot = join(repoRoot, "config/raw");
const compiledRoot = join(repoRoot, "config/compiled");

// `templatePoints` can be either an explicit polyline or a
// procedural shape marker. Keeping the authored form declarative
// means designers can tune the circle resolution without editing
// code, and the compiler is the single place shapes get expanded.
const PolylineSchema = z.object({
  shape: z.literal("polyline"),
  points: z
    .array(
      z.object({
        x: z.number().min(0).max(1),
        y: z.number().min(0).max(1),
      }),
    )
    .min(2),
});

const CircleSchema = z.object({
  shape: z.literal("circle"),
  segments: z.number().int().min(6).max(64),
});

const TemplatePointsSchema = z.discriminatedUnion("shape", [
  PolylineSchema,
  CircleSchema,
]);

const RuneSchema = z.object({
  name: z.string().min(1),
  type: z.enum(["shield", "heal", "purify"]),
  description: z.string().min(1),
  templatePoints: TemplatePointsSchema,
  tolerance: z.number().positive().max(1),
  color: z.string().regex(/^#[0-9a-fA-F]{6}$/),
  glowColor: z.string().min(1),
  manaCost: z.number().int().positive(),
  duration: z.number().int().positive(),
});

function loadDir(dir, schema, kind) {
  const files = readdirSync(dir)
    .filter((f) => f.endsWith(".json"))
    .sort();
  const out = [];
  for (const file of files) {
    const full = join(dir, file);
    const raw = JSON.parse(readFileSync(full, "utf8"));
    const parsed = schema.safeParse(raw);
    if (!parsed.success) {
      console.error(`[compile-content] ${kind} file ${file} failed validation:`);
      console.error(parsed.error.issues);
      process.exit(1);
    }
    out.push(parsed.data);
  }
  return out;
}

function expandTemplatePoints(template) {
  if (template.shape === "polyline") {
    return template.points.map((p) => ({ x: p.x, y: p.y }));
  }
  // Circle: produce `segments + 1` points so the first + last
  // coincide, matching the authored generator the original
  // RUNE_PATTERNS array used.
  const points = [];
  const { segments } = template;
  for (let i = 0; i <= segments; i++) {
    const angle = (i / segments) * Math.PI * 2;
    points.push({
      x: 0.5 + Math.cos(angle) * 0.5,
      y: 0.5 + Math.sin(angle) * 0.5,
    });
  }
  return points;
}

const runes = loadDir(join(rawRoot, "runes"), RuneSchema, "rune").map((r) => ({
  name: r.name,
  type: r.type,
  description: r.description,
  templatePoints: expandTemplatePoints(r.templatePoints),
  tolerance: r.tolerance,
  color: r.color,
  glowColor: r.glowColor,
  manaCost: r.manaCost,
  duration: r.duration,
}));

// Cross-file invariant: every rune `type` must be unique so
// `getRuneByType` remains deterministic.
const seenTypes = new Set();
for (const r of runes) {
  if (seenTypes.has(r.type)) {
    console.error(
      `[compile-content] duplicate rune type "${r.type}" across authored files`,
    );
    process.exit(1);
  }
  seenTypes.add(r.type);
}

mkdirSync(compiledRoot, { recursive: true });
const body = `// Generated by scripts/compile-content.mjs. Do not edit by hand.
// Source of truth: config/raw/runes/*.json.

export const COMPILED_RUNES = ${JSON.stringify(runes, null, 2)} as const;
`;
writeFileSync(join(compiledRoot, "content.ts"), body);
console.log(
  `[compile-content] wrote content.ts: ${runes.length} runes`,
);
